os: windows

language: cpp

branches:
  except: /pr\/.*/

env:
  - WEBHOOK_URL=https://discordapp.com/api/webhooks/575321192244707350/_6JAWIy9nusy8RVBJCO7T0pgf8wX049sVNgC1ILqxlyw5LscpsUK3tGHQIIv_mp3Xf6O

before_script:
  - curl http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/Irrlicht-x64-Visual-Studio-2019-SDK-10.0.17763.0.zip -o irrlicht.zip
  - unzip irrlicht.zip
  - mkdir -p irrlicht/irrlicht
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/include/* irrlicht/irrlicht
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/Irrlicht.dll .
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/Irrlicht.lib .
  - curl http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/SFML-2.5.1.zip -o SFML-2.5.1.zip
  - unzip SFML-2.5.1.zip
  - mv SFML-2.5.1/lib/sfml-audio.lib .
  - mv SFML-2.5.1/include SFML

script:
  - cmake -A x64 CMakeLists.txt
  - cmake --build .

after_failure:
  - bash <(curl -s http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/notify-discord.sh) "`$TRAVIS_BRANCH` Windows build failed."
