os: windows

language: cpp

branches:
  except: /pr\/.*/

env:
  - WEBHOOK_URL=https://discordapp.com/api/webhooks/575321192244707350/_6JAWIy9nusy8RVBJCO7T0pgf8wX049sVNgC1ILqxlyw5LscpsUK3tGHQIIv_mp3Xf6O

before_script:
  - curl http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/Irrlicht-x64-Visual-Studio-2019-SDK-10.0.17763.0.zip -o irrlicht.zip
  - curl http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/SFML-2.5.1.zip -o SFML-2.5.1.zip
  - curl http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/criterion-v2.3.2.tar.bz2 -o criterion.tar.bz2
  - unzip irrlicht.zip
  - mkdir -p irrlicht/irrlicht
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/include/* irrlicht/irrlicht
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/Irrlicht.dll .
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/Irrlicht.lib .
  - unzip SFML-2.5.1.zip
  - mkdir -p SFML
  - mv SFML-2.5.1/lib/sfml-audio.lib .
  - mv SFML-2.5.1/include/SFML SFML
  - tar -xjf criterion.tar.bz2
  - mkdir -p criterion
  - mv criterion-v2.3.2/bin/criterion.dll .
  - mv criterion-v2.3.2/lib/criterion.lib .
  - mv criterion-v2.3.2/include/criterion criterion

script:
  - cmake -A x64 CMakeLists.txt
  - cmake --build .
  - echo "tree /F /A" | cmd
  - pwd
  - mv Debug/tests_run.exe .
  - ./tests_run.exe --verbose -j1

after_failure:
  - bash <(curl -s http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/notify-discord.sh) "\`$TRAVIS_BRANCH\` Windows build **failed**."

after_success:
  - bash <(curl -s http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/notify-discord.sh) "\`$TRAVIS_BRANCH\` Windows build **succeeded**."
