os: windows

language: cpp
compiler: gcc

branches:
  except: /pr\/.*/

before_script:
  - curl http://ec2-34-244-225-15.eu-west-1.compute.amazonaws.com/Irrlicht-x64-Visual-Studio-2019-SDK-10.0.17763.0.zip -o irrlicht.zip
  - unzip irrlicht.zip
  - mkdir -p irrlicht/irrlicht
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/include/* irrlicht/irrlicht
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/Irrlicht.dll .
  - mv Irrlicht\ x64\ Visual\ Studio\ 2019\ SDK\ 10.0.17763.0/Irrlicht.lib .

script:
  - cmake CMakeLists.txt
  - cmake --build .

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST)"