os: windows

language: cpp
compiler: gcc

branches:
  except: /pr\/.*/

script:
  - cmake CMakeLists.txt
  - cmake --build .
  - ls
  - make engine

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST)"